#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : positional
Version  : 1.1.2
Release  : 11
URL      : http://pypi.debian.net/positional/positional-1.1.2.tar.gz
Source0  : http://pypi.debian.net/positional/positional-1.1.2.tar.gz
Summary  : Library to enforce positional or key-word arguments
Group    : Development/Tools
License  : Apache-2.0
Requires: positional-python
Requires: pbr
Requires: wrapt
BuildRequires : configparser-python
BuildRequires : enum34-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: 0001-test.patch

%description
positional
        ==========
        
        A decorator which enforces only some args may be passed positionally.
        
        |PyPi|
        
        |Build Status|
        
        |Documentation Status|
        
        The Basics
        ==========
        
        `positional` provides a decorator which enforces only some args may be passed
        positionally. The idea and some of the code was taken from the oauth2 client
        of the google-api client.
        
        The decorator makes it easy to support Python 3 style key-word only

%package python
Summary: python components for the positional package.
Group: Default

%description python
python components for the positional package.


%prep
%setup -q -n positional-1.1.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1501145883
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1501145883
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
